### ISSUE TITLE
Field transformation using eval

### ISSUE THREAD

**Issue by joaompinto** [mdatapipe/mdatapipe#1]
Example:
```yaml
  - transform using field_eval:
      name: "[:4].lower()"
      age: "/1000"
  - transport using assert:
      name: john
      age: 0.001
```
